In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
plt.switch_backend('module://ipykernel.pylab.backend_inline')
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.optimizers import Adam
from keras.utils import to_categorical
from sklearn.metrics import confusion_matrix
import seaborn as sns

# Load data from .npy files
input_data = np.load('group5_input_data.npy')
target_data = np.load('group5_target_data.npy')
print("input data: ", input_data)
print("target data: ", target_data[:20])

print("input data shape: ", input_data.shape)
print("target data shape: ", target_data.shape)

# Normalize data
scaler = MinMaxScaler()
normalized_input_data = scaler.fit_transform(input_data)
print("Normalized data: ", normalized_input_data) #To improve convergence

# Observe unique combinations
unique_combinations = np.unique(target_data, axis=0)
print("Unique combinations:")
print(unique_combinations)

# Assign integer labels
label_map = {}
for i, combo in enumerate(unique_combinations):
    label_map[tuple(combo)] = i

# Encode your target data using the label map
encoded_labels = np.array([label_map[tuple(combo)] for combo in target_data])

print("Encoded Labels:")
print(encoded_labels[:20])

# Convert to one-hot encoding
one_hot_labels = to_categorical(encoded_labels)
print("One-Hot Encoded Labels:")
print(one_hot_labels[:20])

reverse_label_map = {v: k for k, v in label_map.items()}
# Print label-to-combination mapping
print("Label to Combination Mapping:")
for label, combo in reverse_label_map.items():
    print(f"Label {label}: {combo}")



C:\Users\MAK\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


input data:  [[ -71.21212121   92.42424242    1.07992247]
 [ -65.15151515    4.54545455    1.76714587]
 [ -50.         -137.87878788    0.78539816]
 ...
 [ -83.33333333  -71.21212121    2.84706834]
 [-131.81818182  -31.81818182    4.90873852]
 [  31.81818182  134.84848485    2.94524311]]
target data:  [[0. 1. 1.]
 [0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 0.]]
input data shape:  (498420, 3)
target data shape:  (498420, 3)
Normalized data:  [[0.25773196 0.81443299 0.171875  ]
 [0.27835052 0.51546392 0.28125   ]
 [0.32989691 0.03092784 0.125     ]
 ...
 [0.21649485 0.25773196 0.453125  ]
 [0.05154639 0.39175258 0.78125   ]
 [0.60824742 0.95876289 0.46875   ]]
Unique combinations:
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]]
Encoded Labels:
[2 0 2 4 2 0 4 3 0 1 2 0 5 3 3 0 5 4 5 5]
O